### ISSUE TITLE
Error: Can't subset columns that don't exist. x Column `survey_id` doesn't exist.

### ISSUE THREAD

**Issue by sofiavilchis** [tntp/surveymonkey#73] opened 2021-08-10 17:02 UTC
Hi I have been pulling my surveys for months, and nothing has change in the survey but  yesterday when I try parse_survey , it gives me this error "Error: Can't subset columns that don't exist.
x Column `survey_id` doesn't exist."

**Comment by sfirke** [comment] 2021-08-12 20:44
Hrm, I can't think what this would be - the package hasn't changed and it sounds like your survey hasn't either.  I'll leave the issue open in case it affects others.  Does `browse_surveys()` still work?

**Comment by ForwardDataWorks** [comment] 2021-11-08 16:10
Getting a similar error when attempting `parse_survey`. (`browse_surveys` works, and `fetch_survey_obj` works)

```
New names:
* weight -> weight...4
* weight -> weight...5
* weight -> weight...6
* weight -> weight...7
* weight -> weight...8
* ...
Error: Can't subset columns that don't exist.
x Columns `choice_metadata`, `date_created`, `date_modified`, `ip_address`, and `GoldSlayerID` don't exist.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
Outer names are only allowed for unnamed scalar atomic inputs
```
I have been using this twice a week for about 6 months, and I most recently used it last Thursday. We are using these surveys for Customer Support, so we have about 20 of them that are identical except for the Support Agent's name. I tried a few random survey IDs, and I get the same error.

**Comment by sfirke** [comment] 2021-11-08 17:16
Given that the package is unchanged, and your survey is unchanged, I expect that maybe you installed a newer version of a tidyverse package on which this package depends and that tidyverse package has a breaking change that affects something internal to `parse_survey`.  Might that be the case?

**Comment by ForwardDataWorks** [comment] 2021-11-08 18:09
@sfirke thanks for the quick reply. As I mentioned in my original post, I have been using the surveymonkey package twice a week for the past 6 months (on the same group of surveys), and I used it most recently on **Thursday** of last week. I didn't update any packages in the last four days. Any other suggestions you have would be helpful. I am proficient in R, but I am not a developer.

**Comment by sfirke** [comment] 2021-11-08 19:42
If your survey is the same, and all packages are unchanged including `surveymonkey`, it's hard to think what the culprit might be.  It's possible that SurveyMonkey made a change to their API and is exporting differently, but the documentation looks unchanged and that seems unlikely to me.

You could try that suggestion to run `rlang::last_error()` and see if that log tells anything useful.  I no longer have a SurveyMonkey account and have stepped away from this project.  So I can't fully debug this myself, even if I wanted to.  Maybe @mattroumaya has an idea.

Sorry, I know that's a bummer.  To assign blame for this: at my prior company I asked SurveyMonkey to compensate us in-kind for writing and maintaining this package, but their idea of compensation was inadequate.  My company switched to a competitor product as a result and abandoned this package.  If SurveyMonkey had invested in open source, my former colleagues would still be maintaining it and they could likely troubleshoot this.  The package would probably even be on CRAN and have unit tests written that might surface breakage as a result of changes.

For you or anyone who wants to tackle this, no developer experience needed (just R fluency):

The problem is in https://github.com/tntp/surveymonkey/blob/master/R/assemble.R.   Whoever wants to dig into this, start with `surv_obj < fetch_survey_obj(1234567)` [with your survey ID] to load that object into the environment and then start running the code in that linked file for `parse_survey()` line by line, starting with row 17 where it calls `get_responses`.  Then you'll find precisely which line causes the error, and can look at the objects at the time of the command to see what's going wrong.

**Comment by mattroumaya** [comment] 2021-11-08 19:53
Thanks for the additional info, @sfirke. I actually tried to debug this earlier, but couldn't replicate the issue. I even updated `tidyverse` and other packages to see if it would throw an error across multiple surveys, but had no issues.

@ForwardDataWorks - can you provide any information about the structure of your survey? Any detail you can provide about the types of questions you're using, if there are custom variables or anything unique, would be great. 

Not that you haven't done so, but I feel that it's obligatory to suggest restarting your R session and trying to re-run. 

Also, it's very lame that SurveyMonkey was not willing to adequately compensate for open-source development. This package greatly benefits myself and my colleagues (also enterprise customers), and we would be more inclined to look elsewhere without this package. I'm happy to help maintain it, and add functionality when possible/warranted.

**Comment by ForwardDataWorks** [comment] 2021-11-09 16:34
@mattroumaya Thanks for the code. Unfortunately it is throwing an error:
```
Error in parse_respondent_list(.) : 
  could not find function "parse_respondent_list"
```
Any suggestions/edits you can provide would be greatly appreciated.

**Comment by mattroumaya** [comment] 2021-11-09 16:41
@ForwardDataWorks sorry about that! I updated the code above, if you copy and paste it again and use `parse_survey2`, I am hoping it'll work.

**Comment by ForwardDataWorks** [comment] 2021-11-09 17:10
Ah, brilliant, @mattroumaya !! Thanks for the help.

**Comment by mattroumaya** [comment] 2021-11-09 21:25
Glad it worked for you! I'll submit a PR later to close this out, and you'll be able to update the package, and hopefully won't run into any more issues. I'll also investigate further, because it seems that `choice_metadata` is being brought in for weighted questions, so we'll need to decide how that gets handled.

**Comment by mattroumaya** [comment] 2021-11-10 14:58
PR #76 closes this, you can update the package and should no longer run into this issue. It seems that SurveyMonkey has been doing a bit of work on their API, so we'll have to keep an eye on any similar issues that come up.

**Closed by mattroumaya** 2021-11-10 14:58 UTC

**Comment by sfirke** [comment] 2021-11-10 15:14
Nice work!
